
global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 10s 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'cadvisor'
  - job_name: 'server_fast_metrics'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['server_fast:8000']
  - job_name: 'server_slow_metrics'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['server_slow:8001']
